# Generated by Django 4.0.5 on 2022-07-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
