# Generated by Django 4.0.5 on 2022-07-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0002_alter_imagestore_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagestore',
            old_name='img',
            new_name='image',
        ),
    ]
